# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'Linux-Docker'

container: conorcasey/docker-jll-azdo:vsphere

workspace:
  clean: all

variables:
- group: pTfeRemote
- group: labPaloAlto
- name: certdir
  value: '/usr/local/share/ca-certificates'


steps:
- task: CmdLine@2
  displayName: Add TFE server TLS certificate to container
  inputs:
    script: |
      sudo mkdir -p $(certdir)/tfe
      sudo cp SSL/tfe-server-cert.crt $(certdir)/tfe
      sudo cp SSL/ca-bundle.crt $(certdir)/tfe
      sudo chmod 755 $(certdir)/tfe
      sudo chmod 644 $(certdir)/tfe/*
      sudo update-ca-certificates

- task: CmdLine@2
  displayName: Create .tar.gz of terraform configuration 
  inputs:
    script: tar -zcvf upload.tar.gz -C Terraform .; chmod 777 upload.tar.gz

- task: PythonScript@0
  displayName: Queue terraform job in TFE
  inputs:
    type: filePath
    scriptPath: Scripts/tfe_push.py
    arguments: $(hostname) "Test-prod" "app04" $(token)

- task: PythonScript@0
  displayName: Commit Firewall Updates if necessary
  inputs:
    type: filePath
    scriptPath: Scripts/panos_commit.py
    arguments: $(panos_firewall) $(panos_username) $(panos_password)

